### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by Rui-hue** [UARK-AICV/AOE-Net#3]
hi, I got the following error when running training, do you know how to solve it？
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    main(args)
  File "main.py", line 223, in main
    solver.train(cfg.TRAIN.NUM_EPOCHS)
  File "main.py", line 140, in train
    self.train_epoch(train_loader, bm_mask, epoch, writer)
  File "main.py", line 85, in train_epoch
    confidence_map, start, end = self.model(env_features, agent_features, agent_masks, obj_features, obj_masks)
  File "/home/gpu/anaconda3/envs/ir/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gpu/anaconda3/envs/ir/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/gpu/anaconda3/envs/ir/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/gpu/anaconda3/envs/ir/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/gpu/anaconda3/envs/ir/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/gpu/anaconda3/envs/ir/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/gpu/anaconda3/envs/ir/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1t/liurui/AOE-Net-main/models/model.py", line 140, in forward
    agent_fused_features, selected_agents = self.fuse_agent(agent_features, agent_masks, env_features)
ValueError: too many values to unpack (expected 2)

**Comment by vhvkhoa** [comment]
Hi, thank you for your interest in our work.
I accidentally added `selected_agents` and `selected_objs` into the code for some visualizations.
Please try remove them out on lines 140-141, remove lines 228-229, and only keep `return conf_map, start_map, end_map` at line 231.

**Comment by Rui-hue** [comment]
Thank you very much for your help, and could you share frm_num.pkl and movie_fps.pkl file? What do these two files mean?
